[workspace]
members = [ 
  "basic_screen_manager",
  "basic_window", 
  "camera_platformer_2d", 
  "raylib",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]

